CREATE b_users IF NOT EXISTS (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `LOGIN` CHAR(20) NOT NULL,
    `PASSWORD` VARCHAR NOT NULL,
    `ROLE` CHAR(2) DEFAULT 'R',
    PRIMARY(ID)
);

CREATE b_review IF NOT EXISTS (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `USER_ID` INT NOT NULL,
    `PREFERENCES` TEXT,
    `NEGATIVE` TEXT,
    `COMMENT` TEXT,
    `NOT_EQUALE` CHAR(1) DEFAULT 'N',
    `NOT_EQUALE_TEXT` TEXT,
    `TOTAL_MARK` FLOAT NOT NULL,
    `TOTAL_VOTE` INT,
    PRIMARY(ID)
);

CREATE b_review_props IF NOT EXISTS (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `REVIEW_ID` INT NOT NULL,
    `VOTE` INT NOT NULL,
    PRIMARY(ID)
);

CREATE b_errors IF NOT EXISTS ();